// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartMeterWeb.Data.Context;

#nullable disable

namespace SmartMeterWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AddressId"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("HouseNo")
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("AddressId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Arrear", b =>
                {
                    b.Property<long>("ArrearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArrearId"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("ArrearType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("BillId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaidStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArrearId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Arrears", t =>
                        {
                            t.HasCheckConstraint("CK_Arrear_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_Arrear_PaidStatus", "\"PaidStatus\" IN ('Paid','Unpaid','Partially Paid')");

                            t.HasCheckConstraint("CK_Arrear_Type", "\"ArrearType\" IN ('Overdue','Penalty','Interest')");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Billing", b =>
                {
                    b.Property<long>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BillId"));

                    b.Property<double>("BaseAmount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("BillingPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BillingPeriodStart")
                        .HasColumnType("date");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DisconnectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("TaxAmount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<double>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(18,4)")
                        .HasComputedColumnSql("\"BaseAmount\" + \"TaxAmount\"", true);

                    b.Property<double>("TotalUnitsConsumed")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("BillId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Billings", t =>
                        {
                            t.HasCheckConstraint("CK_Billings_PaidStatus", "\"PaymentStatus\" IN ('Paid','Unpaid','Overdue','Cancelled')");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Consumer", b =>
                {
                    b.Property<long>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConsumerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("ConsumerId");

                    b.HasIndex("Name");

                    b.ToTable("Consumers", t =>
                        {
                            t.HasCheckConstraint("CK_Consumer_timestamp", "\"UpdatedAt\" IS NULL OR \"UpdatedAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.CustomerCareMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("CustomerCareMessages");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Meter", b =>
                {
                    b.Property<string>("MeterSerialNo")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Firmware")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ICCID")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IMSI")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("InstallTsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MeterSerialNo");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Meters", t =>
                        {
                            t.HasCheckConstraint("CK_Meter_Status", "\"Status\" IN ('Active','Inactive','Decommissioned')");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Current")
                        .HasColumnType("double precision");

                    b.Property<double>("EnergyConsumed")
                        .HasColumnType("double precision");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PowerFactor")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReadingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.OrgUnit", b =>
                {
                    b.Property<int>("OrgUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrgUnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrgUnitId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Type");

                    b.ToTable("OrgUnits", t =>
                        {
                            t.HasCheckConstraint("CK_Type", "\"Type\" IN ('Zone','Substation','Feeder','DTR')");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TariffId"));

                    b.Property<double>("BaseRate")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TaxRate")
                        .HasColumnType("double precision");

                    b.HasKey("TariffId");

                    b.ToTable("Tariffs", t =>
                        {
                            t.HasCheckConstraint("CK_Tariff_BaseRate", "\"BaseRate\" > 0");

                            t.HasCheckConstraint("CK_Tariff_Dates", "\"EffectiveTo\" IS NULL OR \"EffectiveFrom\" < \"EffectiveTo\"");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffDetails", b =>
                {
                    b.Property<int>("TariffDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TariffDetailsId"));

                    b.Property<int?>("TariffSlabId")
                        .HasColumnType("integer");

                    b.Property<int?>("TodRuleId")
                        .HasColumnType("integer");

                    b.HasKey("TariffDetailsId");

                    b.HasIndex("TariffSlabId");

                    b.HasIndex("TodRuleId");

                    b.ToTable("TariffDetails");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffSlab", b =>
                {
                    b.Property<int>("TariffSlabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TariffSlabId"));

                    b.Property<double>("FromKwh")
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("RatePerKwh")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer");

                    b.Property<double>("ToKwh")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("TariffSlabId");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffSlabs", t =>
                        {
                            t.HasCheckConstraint("CK_TariffSlab_Range", "\"FromKwh\" >= 0 AND \"ToKwh\" > \"FromKwh\"");

                            t.HasCheckConstraint("CK_TariffSlab_Rate", "\"RatePerKwh\" > 0");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TodRule", b =>
                {
                    b.Property<int>("TodRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodRuleId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RatePerKwh")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer");

                    b.HasKey("TodRuleId");

                    b.HasIndex("Name");

                    b.HasIndex("TariffId");

                    b.ToTable("TodRules", t =>
                        {
                            t.HasCheckConstraint("CK_TodRule_Rate", "\"RatePerKwh\" > 0");

                            t.HasCheckConstraint("CK_TodRule_Time", "\"EndTime\" > \"StartTime\"");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Address", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Arrear", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Billing", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Meter", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.MeterReading", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.OrgUnit", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.OrgUnit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffDetails", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.TariffSlab", "TariffSlab")
                        .WithMany()
                        .HasForeignKey("TariffSlabId");

                    b.HasOne("SmartMeterWeb.Data.Entities.TodRule", "TodRule")
                        .WithMany()
                        .HasForeignKey("TodRuleId");

                    b.Navigation("TariffSlab");

                    b.Navigation("TodRule");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffSlab", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TodRule", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });
#pragma warning restore 612, 618
        }
    }
}
